# Generated by Django 3.2.6 on 2021-12-11 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20211010_2252'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('exampleFormControlTextarea1', models.TextField()),
                ('exampleFormControlTextarea2', models.TextField()),
            ],
        ),
    ]
